---

#------------------------------------------------------------------------------
# YAML Aliases to simplify maintenance

anchorLinks:
  - threshold: &ap
      - {color: "green", level: 1}
      - {color: "red", level: 0}

#------------------------------------------------------------------------------
# Panel Config

cellIdPreamble: "cell-"
cells: 

  ap_it:
    dataRef: "ap_it"
    label:
      units: "ops"
      decimalPoints: 0
    fillColor:
      gradientMode: "hue"
      thresholds: *ap
    link:
      url: "https://grafana.inthepocket.net/a/grafana-synthetic-monitoring-app/checks/42042/dashboard?var-probe=$__all&var-job=ap_it&var-instance=172.16.91.51"
    
  ap_odessey:
    dataRef: "ap_odessey"
    label:
      units: "ops"
      decimalPoints: 0
    labelColor:
      gradientMode: "hue"
      thresholds: *ap
    link:
      url: "https://grafana.inthepocket.net/a/grafana-synthetic-monitoring-app/checks/42046/dashboard?var-probe=$__all&var-job=ap_odessey&var-instance=172.16.91.52"

  ap_nebula:
    dataRef: "ap_nebula"
    label:
      units: "ops"
      decimalPoints: 0
    labelColor:
      gradientMode: "hue"
      thresholds: *ap
    link:
      url: "https://grafana.inthepocket.net/a/grafana-synthetic-monitoring-app/checks/42030/dashboard?var-probe=$__all&var-job=ap_nebula&var-instance=172.16.91.53"

  ap_rocket:
    dataRef: "ap_rocket"
    label:
      units: "ops"
      decimalPoints: 0
    labelColor:
      gradientMode: "hue"
      thresholds: *ap
    link:
      url: "https://grafana.inthepocket.net/a/grafana-synthetic-monitoring-app/checks/42042/dashboard?var-probe=$__all&var-job=ap_it&var-instance=172.16.91.51"

  ap_makerspace:
    dataRef: "ap_makerspace"
    label:
      units: "ops"
      decimalPoints: 0
    labelColor:
      gradientMode: "hue"
      thresholds: *ap
    link:
      url: "https://grafana.inthepocket.net/a/grafana-synthetic-monitoring-app/checks/42042/dashboard?var-probe=$__all&var-job=ap_it&var-instance=172.16.91.51"

  ap_gizmo:
    dataRef: "ap_gizmo"
    label:
      units: "ops"
      decimalPoints: 0
    labelColor:
      gradientMode: "hue"
      thresholds: *ap
    link:
      url: "https://grafana.inthepocket.net/a/grafana-synthetic-monitoring-app/checks/42042/dashboard?var-probe=$__all&var-job=ap_it&var-instance=172.16.91.51"

  ap_silentroom:
    dataRef: "ap_silentroom"
    label:
      units: "ops"
      decimalPoints: 0
    labelColor:
      gradientMode: "hue"
      thresholds: *ap
    link:
      url: "https://grafana.inthepocket.net/a/grafana-synthetic-monitoring-app/checks/42042/dashboard?var-probe=$__all&var-job=ap_it&var-instance=172.16.91.51"

  ap_keuken:
    dataRef: "ap_keuken"
    label:
      units: "ops"
      decimalPoints: 0
    labelColor:
      gradientMode: "hue"
      thresholds: *ap
    link:
      url: "https://grafana.inthepocket.net/a/grafana-synthetic-monitoring-app/checks/42042/dashboard?var-probe=$__all&var-job=ap_it&var-instance=172.16.91.51"

  ap_reception:
    dataRef: "ap_reception"
    label:
      units: "ops"
      decimalPoints: 0
    labelColor:
      gradientMode: "hue"
      thresholds: *ap
    link:
      url: "https://grafana.inthepocket.net/a/grafana-synthetic-monitoring-app/checks/42042/dashboard?var-probe=$__all&var-job=ap_it&var-instance=172.16.91.51"

  ap_orbit:
    dataRef: "ap_orbit"
    label:
      units: "ops"
      decimalPoints: 0
    labelColor:
      gradientMode: "hue"
      thresholds: *ap
    link:
      url: "https://grafana.inthepocket.net/a/grafana-synthetic-monitoring-app/checks/42042/dashboard?var-probe=$__all&var-job=ap_it&var-instance=172.16.91.51"

  ap_bender:
    dataRef: "ap_bender"
    label:
      units: "ops"
      decimalPoints: 0
    labelColor:
      gradientMode: "hue"
      thresholds: *ap
    link:
      url: "https://grafana.inthepocket.net/a/grafana-synthetic-monitoring-app/checks/42042/dashboard?var-probe=$__all&var-job=ap_it&var-instance=172.16.91.51"

  ap_arena:
    dataRef: "ap_arena"
    label:
      units: "ops"
      decimalPoints: 0
    labelColor:
      gradientMode: "hue"
      thresholds: *ap
    link:
      url: "https://grafana.inthepocket.net/a/grafana-synthetic-monitoring-app/checks/42042/dashboard?var-probe=$__all&var-job=ap_it&var-instance=172.16.91.51"

  ap_dory:
    dataRef: "ap_dory"
    label:
      units: "ops"
      decimalPoints: 0
    labelColor:
      gradientMode: "hue"
      thresholds: *ap
    link:
      url: "https://grafana.inthepocket.net/a/grafana-synthetic-monitoring-app/checks/42042/dashboard?var-probe=$__all&var-job=ap_it&var-instance=172.16.91.51"

  ap_grasvlakte:
    dataRef: "ap_grasvlakte"
    label:
      units: "ops"
      decimalPoints: 0
    labelColor:
      gradientMode: "hue"
      thresholds: *ap
    link:
      url: "https://grafana.inthepocket.net/a/grafana-synthetic-monitoring-app/checks/42042/dashboard?var-probe=$__all&var-job=ap_it&var-instance=172.16.91.51"

  ap_poly:
    dataRef: "ap_poly"
    label:
      units: "ops"
      decimalPoints: 0
    labelColor:
      gradientMode: "hue"
      thresholds: *ap
    link:
      url: "https://grafana.inthepocket.net/a/grafana-synthetic-monitoring-app/checks/42042/dashboard?var-probe=$__all&var-job=ap_it&var-instance=172.16.91.51"

  ap_front:
    dataRef: "ap_front"
    label:
      units: "ops"
      decimalPoints: 0
    labelColor:
      gradientMode: "hue"
      thresholds: *ap
    link:
      url: "https://grafana.inthepocket.net/a/grafana-synthetic-monitoring-app/checks/42042/dashboard?var-probe=$__all&var-job=ap_it&var-instance=172.16.91.51"

  ap_center:
    dataRef: "ap_center"
    label:
      units: "ops"
      decimalPoints: 0
    labelColor:
      gradientMode: "hue"
      thresholds: *ap
    link:
      url: "https://grafana.inthepocket.net/a/grafana-synthetic-monitoring-app/checks/42042/dashboard?var-probe=$__all&var-job=ap_it&var-instance=172.16.91.51"

  ap_back:
    dataRef: "ap_back"
    label:
      separator: "cr"
      units: "ops"
      decimalPoints: 0
      labelColor:
        gradientMode: "hue"
        thresholds: *ap
      link:
      url: "https://grafana.inthepocket.net/a/grafana-synthetic-monitoring-app/checks/42042/dashboard?var-probe=$__all&var-job=ap_it&var-instance=172.16.91.51"
